# Generated by Django 3.2.16 on 2025-04-05 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tipo de Notificación')),
                ('resource', models.TextField(blank=True, null=True, verbose_name='Recurso')),
                ('action', models.CharField(blank=True, max_length=100, null=True, verbose_name='Acción')),
                ('api_version', models.CharField(blank=True, max_length=10, null=True, verbose_name='Versión API')),
                ('data_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de los Datos')),
                ('date_created', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Creación')),
                ('notification_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID de Notificación')),
                ('live_mode', models.BooleanField(default=False, verbose_name='Modo en Vivo')),
                ('user_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID del Usuario')),
                ('date_received', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Recepción')),
            ],
            options={
                'verbose_name': 'Notificación de MercadoPago',
                'verbose_name_plural': 'Notificaciones de MercadoPago',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=True, verbose_name='Solicitado')),
                ('pay', models.BooleanField(default=False, verbose_name='Pagado')),
                ('dispatched', models.BooleanField(default=False, verbose_name='Despachado')),
                ('delivered', models.BooleanField(default=False, verbose_name='Entregado')),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('mercadopago_id', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('status_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pago')),
                ('payment_type_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total')),
                ('external_resource_url', models.URLField(blank=True, max_length=500, null=True)),
                ('callback_url', models.URLField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('entity_type', models.CharField(default='individual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.address')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=255, verbose_name='Código')),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Descripción')),
                ('title', models.CharField(max_length=255, verbose_name='Nombre')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Total')),
                ('currency_id', models.CharField(max_length=10)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payment.payment')),
            ],
        ),
    ]
