# Generated by Django 3.2.16 on 2025-05-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='talla',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Talla'),
        ),
    ]
