# Generated by Django 3.2.16 on 2025-04-05 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehome', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('nota', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('pending', models.BooleanField(default=True, verbose_name='Pendiente')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehome.stock', verbose_name='Stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
            },
        ),
    ]
