# Generated by Django 3.2.16 on 2025-04-05 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('custs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0, editable=False, verbose_name='No. Documento')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'E1')], default='E1', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=22)),
                ('concept', models.CharField(blank=True, max_length=80, null=True, verbose_name='Concepto')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custs.tercero', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entrada de mercancía',
                'unique_together': {('number', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Ipdet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('number', models.PositiveIntegerField(default=0, editable=False, verbose_name='Numero')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='Cantidad')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Descuento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='SubTotal')),
                ('talla', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Talla')),
                ('color', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Color')),
                ('codigo', models.CharField(default='', editable=False, max_length=250, verbose_name='Código')),
                ('comments', models.CharField(blank=True, max_length=250, verbose_name='Comentario')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='receipts.ip')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
            },
        ),
    ]
