# Generated by Django 3.2.16 on 2025-04-05 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Apellidos')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Modificado')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Grupo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_superadmin', models.BooleanField(default=False, verbose_name='SuperAdmin')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, max_length=100, verbose_name='Dirección')),
                ('address_line_2', models.CharField(blank=True, max_length=100, verbose_name='Dirección Alterna')),
                ('profile_picture', models.ImageField(blank=True, upload_to='userprofile')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=20, verbose_name='Departamento')),
                ('country', models.CharField(blank=True, max_length=20, verbose_name='País')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Titulo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.CharField(max_length=100, verbose_name='Correo')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='Identificación')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('phone', models.CharField(max_length=100, verbose_name='Teléfono')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('select', models.BooleanField(default=False, verbose_name='Predetermininada')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones de envió',
            },
        ),
    ]
