# Generated by Django 3.2.16 on 2025-04-05 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2, unique=True, verbose_name='Tipo')),
                ('description', models.CharField(max_length=50, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Entrada',
                'verbose_name_plural': 'Tipos de Entradas',
            },
        ),
        migrations.CreateModel(
            name='DocumentOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2, unique=True, verbose_name='Tipo')),
                ('description', models.CharField(max_length=50, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Salida',
                'verbose_name_plural': 'Tipos de Salidas',
            },
        ),
        migrations.CreateModel(
            name='ProductEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Factura No.')),
                ('created_date', models.DateField(verbose_name='Creado')),
                ('deudate', models.DateField(verbose_name='Vencimiento')),
                ('created_date_sistem', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('comments', models.CharField(blank=True, max_length=100, verbose_name='Comentarios')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Proveedor')),
                ('type', models.ForeignKey(default='E1', on_delete=django.db.models.deletion.CASCADE, to='warehome.documententry', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
        ),
        migrations.CreateModel(
            name='ProductOut',
            fields=[
                ('number', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Documento No.')),
                ('created_date', models.DateField(verbose_name='Creado')),
                ('deudate', models.DateField(verbose_name='Vencimiento')),
                ('created_date_sistem', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('comments', models.CharField(blank=True, max_length=100, verbose_name='Comentarios')),
                ('type', models.ForeignKey(default='P1', on_delete=django.db.models.deletion.CASCADE, to='warehome.documentout', verbose_name='Tipo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
            },
        ),
        migrations.CreateModel(
            name='WarehomeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=15, null=True, verbose_name='Descripción')),
                ('qty', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('costo', models.PositiveSmallIntegerField(verbose_name='Costo unitario')),
                ('iva', models.PositiveSmallIntegerField(default=19, verbose_name='Iva')),
                ('ProductEntry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehome.productentry', verbose_name='-')),
                ('ProductOut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehome.productout', verbose_name='-')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventario',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField(editable=False, verbose_name='Cantidad')),
                ('description', models.CharField(blank=True, max_length=15, null=True, verbose_name='Descripción')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProductOut',
            fields=[
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='IP address')),
                ('number', models.BigIntegerField(blank=True, db_index=True, verbose_name='Documento No.')),
                ('created_date', models.DateField(verbose_name='Creado')),
                ('deudate', models.DateField(verbose_name='Vencimiento')),
                ('created_date_sistem', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Modificado')),
                ('comments', models.CharField(blank=True, max_length=100, verbose_name='Comentarios')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, db_constraint=False, default='P1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehome.documentout', verbose_name='Tipo')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'historical Salida',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProductEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='IP address')),
                ('number', models.CharField(db_index=True, max_length=50, verbose_name='Factura No.')),
                ('created_date', models.DateField(verbose_name='Creado')),
                ('deudate', models.DateField(verbose_name='Vencimiento')),
                ('created_date_sistem', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Modificado')),
                ('comments', models.CharField(blank=True, max_length=100, verbose_name='Comentarios')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer', verbose_name='Proveedor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, db_constraint=False, default='E1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehome.documententry', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'historical Entrada',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
