# Generated by Django 3.2.16 on 2025-04-05 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        ('receipts', '0001_initial'),
        ('orders', '0001_initial'),
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', editable=False, max_length=250, verbose_name='Código')),
                ('qty_current', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Ingresan')),
                ('qty_discount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Salen')),
                ('qty_available', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Stock')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True)),
                ('images', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('image_alterna', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Descuento')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio de Venta')),
                ('price1', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio')),
                ('price2', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Mayorista')),
                ('price_old', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo')),
                ('flag', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ref', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('slug', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('active', models.BooleanField(default='True', max_length=5, null=True, verbose_name='Activo')),
                ('soldout', models.BooleanField(default='False', max_length=5, null=True, verbose_name='Agotado')),
                ('offer', models.BooleanField(default='False', max_length=5, null=True, verbose_name='Oferta')),
                ('home', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('talla', models.CharField(blank=True, default='única', max_length=20, null=True, verbose_name='Talla')),
                ('color', models.CharField(blank=True, default='único', max_length=20, null=True, verbose_name='Color')),
                ('service', models.BooleanField(default=False, verbose_name='Servicio')),
                ('item', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Nombre')),
                ('tenant', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
            options={
                'verbose_name': 'Existencia',
                'verbose_name_plural': 'Existencias',
            },
        ),
        migrations.CreateModel(
            name='Itemact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', editable=False, max_length=250, verbose_name='Código')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo')),
                ('qty_ipdet', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Entradas')),
                ('qty_orderdet', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Salidas')),
                ('qty_oedet', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('tipo', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('number', models.CharField(default='0', editable=False, max_length=255)),
                ('talla', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Talla')),
                ('color', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Color')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Descuento')),
                ('ipdet', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='receipts.ipdet', verbose_name='In')),
                ('item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Nombre')),
                ('oedet', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.oedet')),
                ('orderdet', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderdet', verbose_name='Out')),
            ],
            options={
                'verbose_name': 'Actividades de Inventario',
                'verbose_name_plural': 'Actividades de Inventario',
            },
        ),
    ]
