# Generated by Django 3.2.16 on 2025-04-05 16:49

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('paid_until', models.DateField()),
                ('on_trial', models.BooleanField()),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_n', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='No. Documento')),
                ('tipo', models.CharField(choices=[('CEDULA', 'C.C'), ('TARGETA DE IDENTIDAD', 'T.I'), ('NIT', 'Nit')], default='Auto', max_length=20, verbose_name='Tipo de documento')),
                ('email', models.CharField(blank='True', max_length=150, null='True', verbose_name='Correo electrónico')),
                ('company', models.CharField(max_length=100, verbose_name='Razon social')),
                ('address', models.CharField(blank='True', max_length=100, null='True', verbose_name='Dirección')),
                ('phone', models.CharField(blank='True', max_length=100, null='True', verbose_name='Teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tercero',
                'verbose_name_plural': 'Terceros',
            },
        ),
        migrations.CreateModel(
            name='Product_public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('name_extend', models.CharField(max_length=200, unique=True, verbose_name='Nombre Producto')),
                ('qty', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Cantidad')),
                ('images', models.CharField(blank=True, default='', max_length=600, null=True, verbose_name='Imagen')),
                ('image_alterna', models.CharField(blank=True, default='', max_length=600, null=True, verbose_name='Imagen Alterna')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Descripción el producto')),
                ('price1', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Precio Detal')),
                ('price2', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Precio por Mayor')),
                ('price_old', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Precio Anterior')),
                ('flag', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Grupo')),
                ('ref', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Referencia')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Url')),
                ('published_public', models.BooleanField(default=True, verbose_name='Publicado')),
                ('published', models.BooleanField(default=True, verbose_name='Local')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('soldout', models.BooleanField(default=False, verbose_name='Agotado')),
                ('offer', models.BooleanField(default=False, verbose_name='Oferta')),
                ('home', models.BooleanField(default=False, verbose_name='Exclusivo')),
                ('created_date', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Creado')),
                ('modified_date', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Modificado')),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='customers.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
