# Generated by Django 3.2.16 on 2025-04-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_n', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Nit')),
                ('email', models.CharField(blank='True', max_length=150, null='True', verbose_name='Correo electrónico')),
                ('company', models.CharField(max_length=100, verbose_name='Razon social')),
                ('web', models.CharField(blank='True', max_length=100, null='True', verbose_name='Página web')),
                ('address', models.CharField(blank='True', max_length=100, null='True', verbose_name='Dirección')),
                ('phone', models.CharField(blank='True', max_length=100, null='True', verbose_name='Teléfono')),
                ('whatsaap', models.CharField(blank='True', max_length=15, null='True', verbose_name='WhatsApp')),
                ('we', models.TextField(blank='True', max_length=750, null='True', verbose_name='Nosotros')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compañia',
                'verbose_name_plural': 'Compañia',
            },
        ),
    ]
