# Generated by Django 3.2.16 on 2025-04-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('document', models.IntegerField(verbose_name='Nit')),
                ('addres', models.CharField(blank=True, max_length=120, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('supplier', models.BooleanField(default=True, verbose_name='Proveedor')),
                ('cust', models.BooleanField(default=False, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Tercero',
                'verbose_name_plural': 'Terceros',
            },
        ),
    ]
