# Generated by Django 3.2.16 on 2025-04-05 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('custs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0, editable=False, verbose_name='Pedido')),
                ('tipo', models.CharField(choices=[('PEDIDO INTERNO', 'PI'), ('PEDIDO EXTERNO', 'PE')], default='PEDIDO INTERNO', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=22)),
                ('concept', models.CharField(blank=True, max_length=80, null=True, verbose_name='Concepto')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Solicitado')),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custs.tercero', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'unique_together': {('number', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Orderdet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('number', models.PositiveIntegerField(default=0, editable=False)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='Cantidad')),
                ('qtyorder', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=9)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=22, verbose_name='SubTotal')),
                ('comments', models.CharField(blank=True, max_length=100, verbose_name='Comentario')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
            },
        ),
    ]
