# Generated by Django 3.2.16 on 2025-04-05 16:49

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Imagen')),
                ('image_alterna', models.CharField(blank=True, max_length=600, null=True, verbose_name='Imagen Alterna')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('codigo', models.CharField(auto_created=True, max_length=150, primary_key=True, serialize=False, verbose_name='*Código')),
                ('item', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name_extend', models.CharField(max_length=200, unique=True, verbose_name='*Nombre Producto')),
                ('images', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='*Imagen')),
                ('image_alterna', models.CharField(blank=True, default='', max_length=600, null=True, verbose_name='Imagen Alterna')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video')),
                ('description', models.TextField(blank=True, max_length=4000, verbose_name='*Descripción el producto')),
                ('price1', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='P. Detal')),
                ('price2', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='P. Mayor')),
                ('price_old', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Precio Anterior')),
                ('flag', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='*Grupo')),
                ('ref', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='*Referencia')),
                ('qty', models.BigIntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Url')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('soldout', models.BooleanField(default=False, verbose_name='Agotado')),
                ('offer', models.BooleanField(default=False, verbose_name='Oferta')),
                ('published', models.BooleanField(default=True, verbose_name='Publico')),
                ('home', models.BooleanField(default=False, verbose_name='Exclusivo')),
                ('service', models.BooleanField(default=False, verbose_name='Servicio')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen')),
                ('image_alterna', models.CharField(blank=True, max_length=600, null=True, verbose_name='Imagen Alterna')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Galeria de Imagenes',
            },
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Categoría')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Categoria de Producto',
                'verbose_name_plural': 'Categoria de Productos',
            },
        ),
    ]
